Repository NFFT/nfft, pull requests merged in 2025-09, with the labels that each got.

#153 Add dev container.
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement, build routine

#157 Prevent autoreconf warning in nfft_lib_codspeed.m4
  m4/nfft_lib_codspeed.m4
Labels: bug

#162 Run benchmarks agnostic to certain parameters only for default values.
  .github/workflows/build_linux.yml
  benchmarks/Makefile.am
  configure.ac
Labels: chore

#165 Fix compilation errors with GCC 15 in cunit tests
  tests/nfct.c
  tests/nfft.c
  tests/nfst.c
Labels: fix

#143 Added NFSFT interface for Julia and Python
  .gitignore
  configure.ac
  julia/Makefile.am
  julia/nfsft/Makefile.am
  julia/nfsft/NFSFT.jl
  julia/nfsft/libnfsftjulia.c
  julia/nfsft/simple_test.jl
  kernel/nfct/nfct.c
  kernel/nfft/nfft.c
  kernel/nfst/nfst.c
  tests/nfct.c
  tests/nfft.c
  tests/util.c
Labels: feat
